### ISSUE TITLE
Bugs 7/30

### ISSUE THREAD

**Issue by buhrmi** [buka-gaming/server#2]
some bugs found on 7/30

* [x] players can sit in multiple seats
* [x] players can sit in seats outside of seat boundary (eg seat 400, -100)
* [ ] SQL injection attack by sending modified access token
* [x] server doesnt seem to send tablestate to clients without access tokens

**Comment by pillepalle1** [comment]
Bugs 1, 2, 4 solved. SQL injection still pending
