### ISSUE TITLE
Send player's action in seat object

### ISSUE THREAD

**Issue by buhrmi** [buka-gaming/server#9]
When a player does an action, eg fold, it should be saved in the seats array, eg in `seats[2].last_action` so we can display the action that the player has taken.

**Comment by pillepalle1** [comment]
Ok, Encoding as follows:

'F' for Fold
'X' for Check
'C' for Call
'B' for Bet
'R' for Raise

The amount that has been bet or raised _to_ can be taken from the committed property of the Seat object.

TODO: Uodate Wiki after Implementation

**Comment by pillepalle1** [comment]
This action will reset once the hand progresses to the next street.

Example: Right after a player checks on the Flop, his `last_action` contains the value 'X'. Once the Turn is dealt, his `last_action` will contain an empty value or will be undefined.

**Comment by buhrmi** [comment]
can't we just keep it at `Fold` for Fold, `Check` for Check, `Call` for Call, `Bet` for Bet and `Raise` for Raise? lol
